"""create location events table

Revision ID: 289ba37d11ee
Revises: b81c3f419d0f
Create Date: 2026-10-01 09:31:04.579939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289ba37d11ee'
down_revision: Union[str, Sequence[str], None] = 'b81c3f419d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_events_device_id'), 'location_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_location_events_recorded_at'), 'location_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_location_events_user_id'), 'location_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_events_user_id'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_recorded_at'), table_name='location_events')
    op.drop_index(op.f('ix_location_events_device_id'), table_name='location_events')
    op.drop_table('location_events')
    # ### end Alembic commands ###
