"""create geofence events table

Revision ID: 3944691a64b3
Revises: 289ba37d11ee
Create Date: 2026-10-01 10:32:46.903899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3944691a64b3'
down_revision: Union[str, Sequence[str], None] = '289ba37d11ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=False),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_events_device_id'), 'geofence_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_event_type'), 'geofence_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_geofence_events_geofence_id'), 'geofence_events', ['geofence_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_recorded_at'), 'geofence_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_geofence_events_user_id'), 'geofence_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_events_user_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_recorded_at'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_geofence_id'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_event_type'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_device_id'), table_name='geofence_events')
    op.drop_table('geofence_events')
    # ### end Alembic commands ###
