"""add geofences

Revision ID: b81c3f419d0f
Revises: 016b54fd88a1
Create Date: 2026-10-01 07:59:19.508099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81c3f419d0f'
down_revision: Union[str, Sequence[str], None] = '016b54fd88a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('boundary_type', sa.String(length=20), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=True),
    sa.Column('center_longitude', sa.Float(), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofences_boundary_type'), 'geofences', ['boundary_type'], unique=False)
    op.create_index(op.f('ix_geofences_created_by'), 'geofences', ['created_by'], unique=False)
    op.create_index(op.f('ix_geofences_is_active'), 'geofences', ['is_active'], unique=False)
    op.create_table('geofence_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('point_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geofence_points_geofence_id'), 'geofence_points', ['geofence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_points_geofence_id'), table_name='geofence_points')
    op.drop_table('geofence_points')
    op.drop_index(op.f('ix_geofences_is_active'), table_name='geofences')
    op.drop_index(op.f('ix_geofences_created_by'), table_name='geofences')
    op.drop_index(op.f('ix_geofences_boundary_type'), table_name='geofences')
    op.drop_table('geofences')
    # ### end Alembic commands ###
