class AuditAction:
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_ACTIVATED = "USER_ACTIVATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    USER_DELETED = "USER_DELETED"
    USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED"

    GEOFENCE_CREATED = "GEOFENCE_CREATED"
    GEOFENCE_UPDATED = "GEOFENCE_UPDATED"
    GEOFENCE_ENABLED = "GEOFENCE_ENABLED"
    GEOFENCE_DISABLED = "GEOFENCE_DISABLED"
    GEOFENCE_DELETED = "GEOFENCE_DELETED"

    DEVICE_CREATED = "DEVICE_CREATED"
    DEVICE_UPDATED = "DEVICE_UPDATED"
    DEVICE_ACTIVATED = "DEVICE_ACTIVATED"
    DEVICE_DEACTIVATED = "DEVICE_DEACTIVATED"
    DEVICE_DELETED = "DEVICE_DELETED"


class AuditEntity:
    USER = "USER"
    GEOFENCE = "GEOFENCE"
    DEVICE = "DEVICE"